# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
- repo: self

trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'

variables:
  projectName: 'poc'
  projectDir: 'PoC'
  solution: '**/MartinPoC.sln'

steps:
- task: UseDotNet@2
  displayName: Install .NET Core 3.1 SDK
  inputs:
    packageType: 'sdk'
    version: '3.1.100'
    installationPath: '$(Agent.ToolsDirectory)/dotnet'

- task: Docker@2
  inputs:
    containerRegistry: 'Azure Ospri Registry Dev'
    command: 'login'

- task: Docker@2
  displayName: Build and push API image
  inputs:
    containerRegistry: 'Azure Ospri Registry Dev'
    repository: 'martenpoc-api'
    command: 'buildAndPush'
    Dockerfile: '**/PoC/Dockerfile-api'
    buildContext: '$(Build.Repository.LocalPath)'
    tags: '$(Build.BuildNumber)'

- task: Docker@2
  displayName: Build and push API image
  inputs:
    containerRegistry: 'Azure Ospri Registry Dev'
    repository: 'martenpoc-handler'
    command: 'buildAndPush'
    Dockerfile: '**/PoC/Dockerfile-handler'
    buildContext: '$(Build.Repository.LocalPath)'
    tags: '$(Build.BuildNumber)'

- task: Docker@2
  displayName: Build and push API image
  inputs:
    containerRegistry: 'Azure Ospri Registry Dev'
    repository: 'martenpoc-raiser'
    command: 'buildAndPush'
    Dockerfile: '**/PoC/Dockerfile-raiser'
    buildContext: '$(Build.Repository.LocalPath)'
    tags: '$(Build.BuildNumber)'

- task: Docker@2
  displayName: Build and push API image
  inputs:
    containerRegistry: 'Azure Ospri Registry Dev'
    repository: 'martenpoc-db'
    command: 'buildAndPush'
    Dockerfile: '**/PoC/Dockerfile-db'
    buildContext: '$(Build.Repository.LocalPath)'
    tags: '$(Build.BuildNumber)'

- task: CopyFiles@2
  inputs:
    Contents: '**/$(projectDir)/deployment.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: CopyFiles@2
#   inputs:
#     Contents: '**/$(projectDir)/AutomatedTests/**'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
#   displayName: Get Functional Test Scripts

# - task: CopyFiles@2
#   inputs:
#     Contents: '**/$(projectDir)/*.json'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
#   displayName: Copy Swagger Files

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop' 
